spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.google.com
          predicates:
            - Query=url,google

        - id: qq_test
          uri: https://www.qq.com
          predicates:
            - Query=url,qq


        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**


